import fs from "fs/promises"
import path from "path"
import { backupFile, copyDir, copySkillDir, ensureDir, pathExists, sanitizePathName, writeJson, writeText, writeTextSecure } from "../utils/files"
import type { CodexBundle } from "../types/codex"
import type { ClaudeMcpServer } from "../types/claude"
import { transformContentForCodex } from "../utils/codex-content"

const MANAGED_START_MARKER = "# BEGIN Compound Engineering plugin MCP -- do not edit this block"
const MANAGED_END_MARKER = "# END Compound Engineering plugin MCP"
const PREV_START_MARKER = "# BEGIN compound-plugin Claude Code MCP"
const PREV_END_MARKER = "# END compound-plugin Claude Code MCP"
const LEGACY_MARKER = "# MCP servers synced from Claude Code"
const UNMARKED_LEGACY_MARKER = "# Generated by compound-plugin"
const MANAGED_INSTALL_MANIFEST = "install-manifest.json"

type CodexInstallManifest = {
  version: 1
  pluginName: string
  skills: string[]
  prompts: string[]
}

const LEGACY_REMOVED_CODEX_SKILLS: Record<string, string[]> = {
  "compound-engineering": ["reproduce-bug"],
}

const LEGACY_REMOVED_CODEX_PROMPTS: Record<string, string[]> = {
  "compound-engineering": ["reproduce-bug"],
}

export async function writeCodexBundle(outputRoot: string, bundle: CodexBundle): Promise<void> {
  const codexRoot = resolveCodexRoot(outputRoot)
  await ensureDir(codexRoot)

  const pluginName = bundle.pluginName ? sanitizeCodexPathComponent(bundle.pluginName) : undefined
  const manifest = pluginName ? await readInstallManifest(codexRoot, pluginName) : null
  const currentPrompts = bundle.prompts.map((prompt) => `${sanitizePathName(prompt.name)}.md`)

  if (bundle.prompts.length > 0) {
    const promptsDir = path.join(codexRoot, "prompts")
    await cleanupRemovedPrompts(promptsDir, manifest, currentPrompts)
    for (const prompt of bundle.prompts) {
      await writeText(path.join(promptsDir, `${sanitizePathName(prompt.name)}.md`), prompt.content + "\n")
    }
  } else if (pluginName) {
    await cleanupRemovedPrompts(path.join(codexRoot, "prompts"), manifest, [])
  }

  const skillsRoot = pluginName
    ? path.join(codexRoot, pluginName, "skills")
    : path.join(codexRoot, "skills")
  const currentSkills = [
    ...bundle.skillDirs.map((skill) => sanitizePathName(skill.name)),
    ...bundle.generatedSkills.map((skill) => sanitizePathName(skill.name)),
  ]
  await cleanupRemovedSkills(skillsRoot, manifest, currentSkills)

  if (bundle.skillDirs.length > 0) {
    for (const skill of bundle.skillDirs) {
      const targetDir = path.join(skillsRoot, sanitizePathName(skill.name))
      await cleanupCurrentManagedSkillDir(targetDir, manifest, sanitizePathName(skill.name))
      await copySkillDir(
        skill.sourceDir,
        targetDir,
        (content) => transformContentForCodex(content, bundle.invocationTargets, {
          unknownSlashBehavior: "preserve",
        }),
      )
    }
  }

  if (bundle.generatedSkills.length > 0) {
    for (const skill of bundle.generatedSkills) {
      const skillDir = path.join(skillsRoot, sanitizePathName(skill.name))
      await cleanupCurrentManagedSkillDir(skillDir, manifest, sanitizePathName(skill.name))
      await writeText(path.join(skillDir, "SKILL.md"), skill.content + "\n")
      for (const sidecar of skill.sidecarDirs ?? []) {
        await copyDir(sidecar.sourceDir, path.join(skillDir, sidecar.targetName))
      }
    }
  }

  if (pluginName) {
    await ensureDir(skillsRoot)
    await writeInstallManifest(codexRoot, {
      version: 1,
      pluginName,
      skills: currentSkills,
      prompts: currentPrompts,
    })
    await ensureAgentsSkillSymlink(codexRoot, pluginName, skillsRoot)
    await cleanupKnownLegacyCodexArtifacts(codexRoot, pluginName)
  }

  const configPath = path.join(codexRoot, "config.toml")
  const existingConfig = await readFileSafe(configPath)
  const mcpToml = renderCodexConfig(bundle.mcpServers)
  const merged = mergeCodexConfig(existingConfig, mcpToml)
  if (merged !== null) {
    const backupPath = await backupFile(configPath)
    if (backupPath) {
      console.log(`Backed up existing config to ${backupPath}`)
    }
    await writeTextSecure(configPath, merged)
  }
}

function resolveCodexRoot(outputRoot: string): string {
  return path.basename(outputRoot) === ".codex" ? outputRoot : path.join(outputRoot, ".codex")
}

function sanitizeCodexPathComponent(name: string): string {
  return sanitizePathName(name).replace(/[\\/]/g, "-")
}

async function readInstallManifest(codexRoot: string, pluginName: string): Promise<CodexInstallManifest | null> {
  const manifestPath = path.join(codexRoot, pluginName, MANAGED_INSTALL_MANIFEST)
  try {
    const raw = await fs.readFile(manifestPath, "utf8")
    const parsed = JSON.parse(raw) as Partial<CodexInstallManifest>
    if (
      parsed.version === 1 &&
      parsed.pluginName === pluginName &&
      Array.isArray(parsed.skills) &&
      Array.isArray(parsed.prompts)
    ) {
      return parsed as CodexInstallManifest
    }
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
      console.warn(`Ignoring unreadable Codex install manifest at ${manifestPath}.`)
    }
  }
  return null
}

async function writeInstallManifest(codexRoot: string, manifest: CodexInstallManifest): Promise<void> {
  await writeJson(path.join(codexRoot, manifest.pluginName, MANAGED_INSTALL_MANIFEST), manifest)
}

async function cleanupRemovedSkills(
  skillsRoot: string,
  manifest: CodexInstallManifest | null,
  currentSkills: string[],
): Promise<void> {
  if (!manifest) return
  const current = new Set(currentSkills)
  for (const skillName of manifest.skills) {
    if (!current.has(skillName)) {
      await fs.rm(path.join(skillsRoot, skillName), { recursive: true, force: true })
    }
  }
}

async function cleanupRemovedPrompts(
  promptsDir: string,
  manifest: CodexInstallManifest | null,
  currentPrompts: string[],
): Promise<void> {
  if (!manifest) return
  const current = new Set(currentPrompts)
  for (const promptFile of manifest.prompts) {
    if (!current.has(promptFile)) {
      await fs.rm(path.join(promptsDir, promptFile), { force: true })
    }
  }
}

async function cleanupCurrentManagedSkillDir(
  targetDir: string,
  manifest: CodexInstallManifest | null,
  skillName: string,
): Promise<void> {
  if (!manifest?.skills.includes(skillName)) return
  await fs.rm(targetDir, { recursive: true, force: true })
}

async function ensureAgentsSkillSymlink(
  codexRoot: string,
  pluginName: string,
  skillsRoot: string,
): Promise<void> {
  const agentsSkillsDir = path.join(path.dirname(codexRoot), ".agents", "skills")
  const symlinkPath = path.join(agentsSkillsDir, pluginName)
  await ensureDir(agentsSkillsDir)

  try {
    const stat = await fs.lstat(symlinkPath)
    if (stat.isSymbolicLink()) {
      try {
        const existingTarget = await fs.realpath(symlinkPath)
        const desiredTarget = await fs.realpath(skillsRoot)
        if (existingTarget === desiredTarget) return
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
          throw err
        }
      }
      await fs.unlink(symlinkPath)
    } else {
      console.warn(`Skipping ${symlinkPath}: a real file or directory exists there. Remove it manually to replace with the Codex skills symlink.`)
      return
    }
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
      throw err
    }
  }

  await fs.symlink(skillsRoot, symlinkPath, process.platform === "win32" ? "junction" : "dir")
}

async function cleanupKnownLegacyCodexArtifacts(codexRoot: string, pluginName: string): Promise<void> {
  const removedSkills = LEGACY_REMOVED_CODEX_SKILLS[pluginName] ?? []
  for (const skillName of removedSkills) {
    const legacySkillPath = path.join(codexRoot, "skills", skillName)
    await moveLegacyArtifactToBackup(codexRoot, pluginName, "skills", legacySkillPath)
  }

  const removedPrompts = LEGACY_REMOVED_CODEX_PROMPTS[pluginName] ?? []
  for (const promptName of removedPrompts) {
    const legacyPromptPath = path.join(codexRoot, "prompts", `${promptName}.md`)
    await moveLegacyArtifactToBackup(codexRoot, pluginName, "prompts", legacyPromptPath)
  }
}

async function moveLegacyArtifactToBackup(
  codexRoot: string,
  pluginName: string,
  kind: "skills" | "prompts",
  artifactPath: string,
): Promise<void> {
  if (!(await pathExists(artifactPath))) return
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-")
  const backupDir = path.join(codexRoot, pluginName, "legacy-backup", timestamp, kind)
  const backupPath = path.join(backupDir, path.basename(artifactPath))
  await ensureDir(backupDir)
  await fs.rename(artifactPath, backupPath)
  console.warn(`Moved legacy Codex ${kind.slice(0, -1)} artifact to ${backupPath}`)
}

export function renderCodexConfig(mcpServers?: Record<string, ClaudeMcpServer>): string | null {
  if (!mcpServers || Object.keys(mcpServers).length === 0) return null

  const lines: string[] = []

  for (const [name, server] of Object.entries(mcpServers)) {
    if (!server.command && !server.url) continue

    const key = formatTomlKey(name)
    lines.push(`[mcp_servers.${key}]`)

    if (server.command) {
      lines.push(`command = ${formatTomlString(server.command)}`)
      if (server.args && server.args.length > 0) {
        const args = server.args.map((arg) => formatTomlString(arg)).join(", ")
        lines.push(`args = [${args}]`)
      }

      if (server.env && Object.keys(server.env).length > 0) {
        lines.push("")
        lines.push(`[mcp_servers.${key}.env]`)
        for (const [envKey, value] of Object.entries(server.env)) {
          lines.push(`${formatTomlKey(envKey)} = ${formatTomlString(value)}`)
        }
      }
    } else if (server.url) {
      lines.push(`url = ${formatTomlString(server.url)}`)
      if (server.headers && Object.keys(server.headers).length > 0) {
        lines.push(`http_headers = ${formatTomlInlineTable(server.headers)}`)
      }
    }

    lines.push("")
  }

  return lines.length > 0 ? lines.join("\n") : null
}

async function readFileSafe(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, "utf-8")
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
      throw err
    }
    return ""
  }
}

export function mergeCodexConfig(existingContent: string, mcpToml: string | null): string | null {
  // Strip current and previous managed blocks
  let stripped = existingContent
  let removedManagedBlock = false
  for (const [start, end] of [[MANAGED_START_MARKER, MANAGED_END_MARKER], [PREV_START_MARKER, PREV_END_MARKER]]) {
    const next = stripped.replace(
      new RegExp(`${escapeForRegex(start)}[\\s\\S]*?${escapeForRegex(end)}\\n?`, "g"),
      "",
    )
    if (next !== stripped) removedManagedBlock = true
    stripped = next
  }

  // No MCP servers to write — only remove bounded managed blocks. Do not strip
  // unmarked legacy markers here: old Codex config files may contain user
  // settings after "# Generated by compound-plugin", and there is no safe
  // boundary for deleting only plugin-owned TOML.
  if (!mcpToml) {
    if (!existingContent) return null
    const legacyMarkerIndex = stripped.indexOf(LEGACY_MARKER)
    if (legacyMarkerIndex !== -1) {
      return stripped.slice(0, legacyMarkerIndex).trimEnd()
    }
    return removedManagedBlock ? stripped.trimEnd() : existingContent
  }

  stripped = stripped.trimEnd()

  // Strip from legacy markers to end of content (old formats wrote everything after the marker)
  let cleaned = stripped
  for (const marker of [LEGACY_MARKER, UNMARKED_LEGACY_MARKER]) {
    const idx = cleaned.indexOf(marker)
    if (idx !== -1) {
      cleaned = cleaned.slice(0, idx).trimEnd()
    }
  }

  const managedBlock = [
    MANAGED_START_MARKER,
    mcpToml.trim(),
    MANAGED_END_MARKER,
    "",
  ].join("\n")

  return cleaned
    ? `${cleaned}\n\n${managedBlock}`
    : `${managedBlock}`
}

function escapeForRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function formatTomlString(value: string): string {
  return JSON.stringify(value)
}

function formatTomlKey(value: string): string {
  if (/^[A-Za-z0-9_-]+$/.test(value)) return value
  return JSON.stringify(value)
}

function formatTomlInlineTable(entries: Record<string, string>): string {
  const parts = Object.entries(entries).map(
    ([key, value]) => `${formatTomlKey(key)} = ${formatTomlString(value)}`,
  )
  return `{ ${parts.join(", ")} }`
}
